
export const LIST_COUNT_MONTH = 'LIST_COUNT_MONTH';
export const LIST_COUNT_GRAPH = 'LIST_COUNT_GRAPH';
export const LIST_GRAPH = 'LIST_GRAPH';
export const USER_BY_TYPE = 'USER_BY_TYPE';
export const SET_STATISTIC_DEFAULT = 'SET_STATISTIC_DEFAULT';
export const HANDLE_STATISTIC_CHANGE = 'HANDLE_STATISTIC_CHANGE';
